include:
  - 'https://gitlab-templates.ddbuild.io/slack-notifier/v3-sdm/template.yml'

stages:
  - check-release
  - notify

check-release:is-published:
  tags: [ "arch:amd64" ]
  image: $CI_IMAGE_DOCKER
  stage: check-release
  id_tokens:
    DDOCTOSTS_ID_TOKEN:
      aud: dd-octo-sts
  script:
    - export GITHUB_TOKEN=$(dd-octo-sts token --scope DataDog/dd-sdk-android --policy self.gitlab.read)
    - bash ./ci/scripts/check_latest_release_is_published.sh

notify:report-failure-to-slack:
  extends: .slack-notifier-base
  stage: notify
  when: on_failure
  script:
    - BUILD_URL="$CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID"
    - 'MESSAGE_TEXT=":status_alert: Some release artifacts were not published to maven. $BUILD_URL"'
    - postmessage "#mobile-sdk-ops" "$MESSAGE_TEXT"
