include:
  - 'https://gitlab-templates.ddbuild.io/slack-notifier/v1/template.yml'

# SETUP

stages:
  - ci-image
  - security
  - publish
  - notify

.snippets:
  # macOS AMI will already have cmdline-tools installed
  install-android-api-components:
    - echo y | ~/android_sdk/cmdline-tools/latest/bin/sdkmanager --install "emulator"
    - echo y | ~/android_sdk/cmdline-tools/latest/bin/sdkmanager --install "platform-tools"
    - echo y | ~/android_sdk/cmdline-tools/latest/bin/sdkmanager --install "$ANDROID_PLATFORM"
    - echo y | ~/android_sdk/cmdline-tools/latest/bin/sdkmanager --install "$ANDROID_BUILD_TOOLS"
    - echo y | ~/android_sdk/cmdline-tools/latest/bin/sdkmanager --install "$ANDROID_EMULATOR_IMAGE"
    - yes | ~/android_sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true
    - echo "no" | ~/android_sdk/cmdline-tools/latest/bin/avdmanager --verbose create avd --force --name "$EMULATOR_NAME" --package "$ANDROID_EMULATOR_IMAGE"
  run-legacy-integration-instrumented:
    - set +e
    - exit_code=0
    - $ANDROID_HOME/emulator/emulator -avd "$EMULATOR_NAME" -grpc-use-jwt -no-snapstorage -no-audio -no-window -no-boot-anim -verbose -qemu -machine virt &
    - GRADLE_OPTS="-Xmx3072m" ./gradlew :instrumented:integration:connectedDebugAndroidTest --stacktrace --no-daemon $( (( $ANDROID_API <= 23 )) && echo "-Puse-api21-java-backport -Puse-desugaring" ) || exit_code=$?
    - $ANDROID_HOME/platform-tools/adb emu kill
    - if [[ "$exit_code" -ne 0 ]]; then exit 1; fi
    - exit 0
  run-core-it-instrumented:
    - set +e
    - exit_code=0
    - $ANDROID_HOME/emulator/emulator -avd "$EMULATOR_NAME" -grpc-use-jwt -no-snapstorage -no-audio -no-window -no-boot-anim -verbose -qemu -machine virt &
    - GRADLE_OPTS="-Xmx3072m" ./gradlew :reliability:core-it:connectedDebugAndroidTest --stacktrace --no-daemon $( (( $ANDROID_API <= 23 )) && echo "-Puse-api21-java-backport -Puse-desugaring" ) || exit_code=$?
    - $ANDROID_HOME/platform-tools/adb emu kill
    - if [[ "$exit_code" -ne 0 ]]; then exit 1; fi
    - exit 0
  set-publishing-credentials:
    - aws ssm get-parameter --region us-east-1 --name ci.dd-sdk-android.gradle-properties --with-decryption --query "Parameter.Value" --out text >> ./gradle.properties
    - export GPG_PRIVATE_KEY=$(aws ssm get-parameter --region us-east-1 --name ci.dd-sdk-android.signing.gpg_private_key --with-decryption --query "Parameter.Value" --out text)
    - export GPG_PASSWORD=$(aws ssm get-parameter --region us-east-1 --name ci.dd-sdk-android.signing.gpg_passphrase --with-decryption --query "Parameter.Value" --out text)
    - export CENTRAL_PUBLISHER_USERNAME=$(aws ssm get-parameter --region us-east-1 --name ci.dd-sdk-android.publishing.central_username --with-decryption --query "Parameter.Value" --out text)
    - export CENTRAL_PUBLISHER_PASSWORD=$(aws ssm get-parameter --region us-east-1 --name ci.dd-sdk-android.publishing.central_password --with-decryption --query "Parameter.Value" --out text)
    - export GPG_PUBLIC_FINGERPRINT=$(aws ssm get-parameter --region us-east-1 --name ci.dd-sdk-android.signing.gpg_public_key --with-decryption --query "Parameter.Value" --out text | gpg --import --import-options show-only | grep -E -o -e "[A-F0-9]{40}")

# CI IMAGE

ci-image:
  stage: ci-image
  when: manual
  except: [ tags, schedules ]
  tags: [ "arch:amd64" ]
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/docker:24.0.4-jammy
  script:
    - docker buildx build --tag $CI_IMAGE_DOCKER -f ./ci/Dockerfile.gitlab --push .

# SECURITY

create_key:
  stage: security
  when: manual
  tags: [ "arch:amd64" ]
  variables:
    PROJECT_NAME: "dd-sdk-android"
    EXPORT_TO_KEYSERVER: "true"
  image: 486234852809.dkr.ecr.us-east-1.amazonaws.com/ci/agent-key-management-tools/gpg:1
  script:
    - /create.sh
  artifacts:
    expire_in: 13 mos
    paths:
      - pubkeys


# TODO RUM-1622 cleanup this section
# TESTS

# PUBLISH ARTIFACTS ON MAVEN

publish:release-core:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :dd-sdk-android-core:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - dd-sdk-android-core/verification-metadata.xml

publish:release-internal:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [ .snippets, set-publishing-credentials ]
    - ./gradlew :dd-sdk-android-internal:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - dd-sdk-android-internal/verification-metadata.xml

# region Publish features/*
publish:release-trace-api:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :features:dd-sdk-android-trace-api:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - features/dd-sdk-android-trace-api/verification-metadata.xml

publish:release-trace-internal:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [ .snippets, set-publishing-credentials ]
    - ./gradlew :features:dd-sdk-android-trace-internal:publishToSonatype --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - features/dd-sdk-android-trace-internal/verification-metadata.xml

publish:release-trace:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :features:dd-sdk-android-trace:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - features/dd-sdk-android-trace/verification-metadata.xml

publish:release-trace-otel:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :features:dd-sdk-android-trace-otel:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - features/dd-sdk-android-trace-otel/verification-metadata.xml

publish:release-logs:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :features:dd-sdk-android-logs:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - features/dd-sdk-android-logs/verification-metadata.xml

publish:release-rum:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :features:dd-sdk-android-rum:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - features/dd-sdk-android-rum/verification-metadata.xml

publish:release-ndk:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :features:dd-sdk-android-ndk:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - features/dd-sdk-android-ndk/verification-metadata.xml

publish:release-session-replay:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :features:dd-sdk-android-session-replay:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - features/dd-sdk-android-session-replay/verification-metadata.xml

publish:release-session-replay-material:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :features:dd-sdk-android-session-replay-material:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - features/dd-sdk-android-session-replay-material/verification-metadata.xml

publish:release-session-replay-compose:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :features:dd-sdk-android-session-replay-compose:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - features/dd-sdk-android-session-replay-compose/verification-metadata.xml

publish:release-webview:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :features:dd-sdk-android-webview:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - features/dd-sdk-android-webview/verification-metadata.xml

# endregion

# region Publish integrations/*

publish:release-coil:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :integrations:dd-sdk-android-coil:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - integrations/dd-sdk-android-coil/verification-metadata.xml

publish:release-compose:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :integrations:dd-sdk-android-compose:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - integrations/dd-sdk-android-compose/verification-metadata.xml

publish:release-fresco:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :integrations:dd-sdk-android-fresco:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - integrations/dd-sdk-android-fresco/verification-metadata.xml

publish:release-glide:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :integrations:dd-sdk-android-glide:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - integrations/dd-sdk-android-glide/verification-metadata.xml

publish:release-trace-coroutines:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :integrations:dd-sdk-android-trace-coroutines:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - integrations/dd-sdk-android-trace-coroutines/verification-metadata.xml

publish:release-rum-coroutines:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :integrations:dd-sdk-android-rum-coroutines:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - integrations/dd-sdk-android-rum-coroutines/verification-metadata.xml

publish:release-rx:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :integrations:dd-sdk-android-rx:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - integrations/dd-sdk-android-rx/verification-metadata.xml

publish:release-sqldelight:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :integrations:dd-sdk-android-sqldelight:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - integrations/dd-sdk-android-sqldelight/verification-metadata.xml

publish:release-timber:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :integrations:dd-sdk-android-timber:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - integrations/dd-sdk-android-timber/verification-metadata.xml

publish:release-android-tv:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :integrations:dd-sdk-android-tv:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - integrations/dd-sdk-android-tv/verification-metadata.xml

publish:release-okhttp:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :integrations:dd-sdk-android-okhttp:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - integrations/dd-sdk-android-okhttp/verification-metadata.xml

publish:release-okhttp-otel:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :integrations:dd-sdk-android-okhttp-otel:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - integrations/dd-sdk-android-okhttp-otel/verification-metadata.xml

# endregion

publish:release-benchmark:
  tags: [ "arch:amd64" ]
  when: manual
  image: $CI_IMAGE_DOCKER
  stage: publish
  timeout: 30m
  script:
    - !reference [.snippets, set-publishing-credentials]
    - ./gradlew :tools:benchmark:publishToSonatype closeSonatypeStagingRepository --stacktrace --no-daemon
  artifacts:
    when: on_success
    expire_in: 7 days
    paths:
      - tools/benchmark/verification-metadata.xml


# SLACK NOTIFICATIONS

notify:publish-develop-success:
  extends: .slack-notifier-base
  stage: notify
  when: on_success
  only:
    - develop
  script:
    - 'MESSAGE_TEXT=":package: $CI_PROJECT_NAME develop $CI_COMMIT_TAG: Snapshot published on :maven:, Sample app published on :synthetics:"'
    - postmessage "#mobile-sdk-ops" "$MESSAGE_TEXT"

notify:publish-develop-failure:
  extends: .slack-notifier-base
  stage: notify
  when: on_failure
  only:
    - develop
  script:
    - BUILD_URL="$CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID"
    - 'MESSAGE_TEXT=":status_alert: $CI_PROJECT_NAME $CI_COMMIT_TAG develop pipeline <$BUILD_URL|$COMMIT_MESSAGE> failed."'
    - postmessage "#mobile-sdk-ops" "$MESSAGE_TEXT"

notify:publish-release-success:
  extends: .slack-notifier-base
  stage: notify
  when: on_success
  only:
    - tags
  script:
    - MAVEN_URL="https://search.maven.org/artifact/com.datadoghq/dd-sdk-android-core/$CI_COMMIT_TAG/aar"
    - 'MESSAGE_TEXT=":rocket: $CI_PROJECT_NAME $CI_COMMIT_TAG published on :maven: $MAVEN_URL"'
    - postmessage "#mobile-sdk-ops" "$MESSAGE_TEXT"

notify:publish-release-failure:
  extends: .slack-notifier-base
  stage: notify
  when: on_failure
  only:
    - tags
  script:
    - BUILD_URL="$CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID"
    - 'MESSAGE_TEXT=":status_alert: $CI_PROJECT_NAME $CI_COMMIT_TAG publish pipeline <$BUILD_URL|$COMMIT_MESSAGE> failed."'
    - postmessage "#mobile-sdk-ops" "$MESSAGE_TEXT"

notify:dogfood-app:
  tags: [ "arch:amd64" ]
  only:
    - tags
  image: $CI_IMAGE_DOCKER
  id_tokens:
    DDOCTOSTS_ID_TOKEN:
      aud: dd-octo-sts
  stage: notify
  when: on_success
  script:
    - export GITHUB_TOKEN=$(dd-octo-sts token --scope DataDog/datadog-android --policy all.gitlab.pr)
    - pip3 install GitPython requests
    - python3 ./ci/scripts/dogfood.py -v $CI_COMMIT_TAG -t app

notify:dogfood-demo:
  tags: [ "arch:amd64" ]
  only:
    - tags
  image: $CI_IMAGE_DOCKER
  id_tokens:
    DDOCTOSTS_ID_TOKEN:
      aud: dd-octo-sts
  stage: notify
  when: on_success
  script:
    - export GITHUB_TOKEN=$(dd-octo-sts token --scope DataDog/shopist-android --policy all.gitlab.pr)
    - pip3 install GitPython requests
    - python3 ./ci/scripts/dogfood.py -v $CI_COMMIT_TAG -t demo

notify:dogfood-gradle-plugin:
  tags: [ "arch:amd64" ]
  only:
    - tags
  image: $CI_IMAGE_DOCKER
  id_tokens:
    DDOCTOSTS_ID_TOKEN:
      aud: dd-octo-sts
  stage: notify
  when: on_success
  script:
    - export GITHUB_TOKEN=$(dd-octo-sts token --scope DataDog/dd-sdk-android-gradle-plugin --policy all.gitlab.pr)
    - pip3 install GitPython requests
    - python3 ./ci/scripts/dogfood.py -v $CI_COMMIT_TAG -t gradle-plugin

notify:merge-verification-metadata:
  tags: [ "arch:amd64" ]
  only:
    - tags
  image: $CI_IMAGE_DOCKER
  stage: notify
  when: on_success
  dependencies:
    - publish:release-core
    - publish:release-internal
    - publish:release-trace
    - publish:release-trace-otel
    - publish:release-logs
    - publish:release-rum
    - publish:release-ndk
    - publish:release-session-replay
    - publish:release-session-replay-material
    - publish:release-session-replay-compose
    - publish:release-webview
    - publish:release-coil
    - publish:release-compose
    - publish:release-fresco
    - publish:release-glide
    - publish:release-trace-coroutines
    - publish:release-rum-coroutines
    - publish:release-rx
    - publish:release-sqldelight
    - publish:release-timber
    - publish:release-android-tv
    - publish:release-okhttp
    - publish:release-okhttp-otel
    - publish:release-benchmark
  script:
    - python3 ./ci/scripts/merge_verification_metadata.py
  artifacts:
    when: on_success
    expire_in: 3 mos
    paths:
      - verification-metadata.xml

