flowchart TB
    subgraph Segment1
    native_record["Native Record | T2"]
    native_record["Native Record  | T3"]
    end
    subgraph Segment2
    web_record["Web Record | T1"]
    native_record["Native Record | T4"]
    native_record["Native Record | T5"]
    end

