#
# Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2016-Present Datadog, Inc.
#
org.gradle.jvmargs=-Xmx6144m
org.gradle.caching=true
org.gradle.configuration-cache=true
# TODO RUM-17809: Let this soak for a bit before switching to enforcement
org.gradle.configuration-cache.problems=warn
org.gradle.parallel=true
org.gradle.tooling.parallel=true
android.useAndroidX=true
android.experimental.enableTestFixturesKotlinSupport=true
# AGP 8.13.2 was tested up to compile SDK 36.1; suppress the warning while we compile against SDK 37
android.suppressUnsupportedCompileSdk=37
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true

# Allows Kotlin with target JVM compat 17 to be built on JDK 21
kotlin.jvm.target.validation.mode = IGNORE

# TODO RUM-18189
# Kotlin 2.0 is not compatible with new DSL APIs enforced in AGP 9 by default. This option will
# be removed in AGP 10 (2027-2028?)
android.newDsl=false
android.builtInKotlin=false

# Changed from false to true by default on AGP 8 -> AGP 9, putting the old behavior
android.onlyEnableUnitTestForTheTestedBuildType=false

# Leave the next line blank for CI
