/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2016-Present Datadog, Inc.
 */

package com.datadog.gradle.plugin.checklicenses

import me.xdrop.fuzzywuzzy.FuzzySearch

object SPDXLicenceConverter {

    fun convert(licenses: String): List<SPDXLicense>? {
        val result = licenses.split('/')
            .map {
                convertLicense(
                    it
                )
            }

        return if (result.isEmpty() || result.contains(null)) {
            null
        } else {
            result.filterNotNull()
        }
    }

    private fun convertLicense(license: String): SPDXLicense? {
        if (license.isBlank()) return null

        val nameMatch = FuzzySearch.extractOne(license.trim(),
            nameList
        )
        if (nameMatch.score > 90) {
            // println("matched name ${nameMatch.score}% [$license] to [${nameMatch.string}]")
            return nameMap[nameMatch.string]
        }

        val identifierMatch = FuzzySearch.extractOne(license.trim(),
            identifierList
        )
        if (identifierMatch.score > 90) {
            // println("matched identifier ${identifierMatch.score}% [$license] to [${identifierMatch.string}]")
            return identifierMap[identifierMatch.string]
        }

        // println(" ? no match for [$license]")
        // println("     closest name [${nameMatch.string}] ${nameMatch.score}%")
        // println("     closest id   [${identifierMatch.string}] ${identifierMatch.score}%")
        return null
    }

    private val identifierMap = SPDXLicense.values()
        .map { it.csvName to it }
        .toMap()

    private val nameMap = mapOf(
        "BSD Zero Clause License" to SPDXLicense._0BSD,
        "Attribution Assurance License" to SPDXLicense.AAL,
        "Abstyles License" to SPDXLicense.ABSTYLES,
        "Adobe Systems Incorporated Source Code License Agreement" to SPDXLicense.ADOBE_2006,
        "Adobe Glyph List License" to SPDXLicense.ADOBE_GLYPH,
        "Amazon Digital Services License" to SPDXLicense.ADSL,
        "Academic Free License v1.1" to SPDXLicense.AFL_1_1,
        "Academic Free License v1.2" to SPDXLicense.AFL_1_2,
        "Academic Free License v2.0" to SPDXLicense.AFL_2_0,
        "Academic Free License v2.1" to SPDXLicense.AFL_2_1,
        "Academic Free License v3.0" to SPDXLicense.AFL_3_0,
        "Afmparse License" to SPDXLicense.AFMPARSE,
        "Affero General Public License v1.0 only" to SPDXLicense.AGPL_1_0_ONLY,
        "Affero General Public License v1.0 or later" to SPDXLicense.AGPL_1_0_OR_LATER,
        "GNU Affero General Public License v3.0 only" to SPDXLicense.AGPL_3_0_ONLY,
        "GNU Affero General Public License v3.0 or later" to SPDXLicense.AGPL_3_0_OR_LATER,
        "Aladdin Free Public License" to SPDXLicense.ALADDIN,
        "AMD's plpa_map.c License" to SPDXLicense.AMDPLPA,
        "Apple MIT License" to SPDXLicense.AML,
        "Academy of Motion Picture Arts and Sciences BSD" to SPDXLicense.AMPAS,
        "ANTLR Software Rights Notice" to SPDXLicense.ANTLR_PD,
        "Apache License 1.0" to SPDXLicense.APACHE_1_0,
        "Apache License 1.1" to SPDXLicense.APACHE_1_1,
        "Apache License 2.0" to SPDXLicense.APACHE_2_0,
        "The Apache License, Version 2.0" to SPDXLicense.APACHE_2_0,
        "Adobe Postscript AFM License" to SPDXLicense.APAFML,
        "Adaptive Public License 1.0" to SPDXLicense.APL_1_0,
        "Apple Public Source License 1.0" to SPDXLicense.APSL_1_0,
        "Apple Public Source License 1.1" to SPDXLicense.APSL_1_1,
        "Apple Public Source License 1.2" to SPDXLicense.APSL_1_2,
        "Apple Public Source License 2.0" to SPDXLicense.APSL_2_0,
        "Artistic License 1.0" to SPDXLicense.ARTISTIC_1_0,
        "Artistic License 1.0 w/clause 8" to SPDXLicense.ARTISTIC_1_0_CL8,
        "Artistic License 1.0 (Perl)" to SPDXLicense.ARTISTIC_1_0_PERL,
        "Artistic License 2.0" to SPDXLicense.ARTISTIC_2_0,
        "Bahyph License" to SPDXLicense.BAHYPH,
        "Barr License" to SPDXLicense.BARR,
        "Beerware License" to SPDXLicense.BEERWARE,
        "BitTorrent Open Source License v1.0" to SPDXLicense.BITTORRENT_1_0,
        "BitTorrent Open Source License v1.1" to SPDXLicense.BITTORRENT_1_1,
        "SQLite Blessing" to SPDXLicense.BLESSING,
        "Blue Oak Model License 1.0.0" to SPDXLicense.BLUEOAK_1_0_0,
        "Borceux license" to SPDXLicense.BORCEUX,
        "BSD 1-Clause License" to SPDXLicense.BSD_1_CLAUSE,
        "BSD 2-Clause \"Simplified\" License" to SPDXLicense.BSD_2_CLAUSE,
        "BSD 2-Clause FreeBSD License" to SPDXLicense.BSD_2_CLAUSE_FREEBSD,
        "BSD 2-Clause NetBSD License" to SPDXLicense.BSD_2_CLAUSE_NETBSD,
        "BSD-2-Clause Plus Patent License" to SPDXLicense.BSD_2_CLAUSE_PATENT,
        "BSD 3-Clause \"New\" or \"Revised\" License" to SPDXLicense.BSD_3_CLAUSE,
        "BSD with attribution" to SPDXLicense.BSD_3_CLAUSE_ATTRIBUTION,
        "BSD 3-Clause Clear License" to SPDXLicense.BSD_3_CLAUSE_CLEAR,
        "Lawrence Berkeley National Labs BSD variant license" to SPDXLicense.BSD_3_CLAUSE_LBNL,
        "BSD 3-Clause No Nuclear License" to SPDXLicense.BSD_3_CLAUSE_NO_NUCLEAR_LICENSE,
        "BSD 3-Clause No Nuclear License 2014" to SPDXLicense.BSD_3_CLAUSE_NO_NUCLEAR_LICENSE_2014,
        "BSD 3-Clause No Nuclear Warranty" to SPDXLicense.BSD_3_CLAUSE_NO_NUCLEAR_WARRANTY,
        "BSD 3-Clause Open MPI variant" to SPDXLicense.BSD_3_CLAUSE_OPEN_MPI,
        "BSD 4-Clause \"Original\" or \"Old\" License" to SPDXLicense.BSD_4_CLAUSE,
        "BSD-4-Clause (University of California-Specific)" to SPDXLicense.BSD_4_CLAUSE_UC,
        "BSD Protection License" to SPDXLicense.BSD_PROTECTION,
        "BSD Source Code Attribution" to SPDXLicense.BSD_SOURCE_CODE,
        "Boost Software License 1.0" to SPDXLicense.BSL_1_0,
        "Bouncy Castle Licence" to SPDXLicense.BOUNCY_CASTLE,
        "bzip2 and libbzip2 License v1.0.5" to SPDXLicense.BZIP2_1_0_5,
        "bzip2 and libbzip2 License v1.0.6" to SPDXLicense.BZIP2_1_0_6,
        "Caldera License" to SPDXLicense.CALDERA,
        "Computer Associates Trusted Open Source License 1.1" to SPDXLicense.CATOSL_1_1,
        "Creative Commons Attribution 1.0 Generic" to SPDXLicense.CC_BY_1_0,
        "Creative Commons Attribution 2.0 Generic" to SPDXLicense.CC_BY_2_0,
        "Creative Commons Attribution 2.5 Generic" to SPDXLicense.CC_BY_2_5,
        "Creative Commons Attribution 3.0 Unported" to SPDXLicense.CC_BY_3_0,
        "Creative Commons Attribution 4.0 International" to SPDXLicense.CC_BY_4_0,
        "Creative Commons Attribution Non Commercial 1.0 Generic" to SPDXLicense.CC_BY_NC_1_0,
        "Creative Commons Attribution Non Commercial 2.0 Generic" to SPDXLicense.CC_BY_NC_2_0,
        "Creative Commons Attribution Non Commercial 2.5 Generic" to SPDXLicense.CC_BY_NC_2_5,
        "Creative Commons Attribution Non Commercial 3.0 Unported" to SPDXLicense.CC_BY_NC_3_0,
        "Creative Commons Attribution Non Commercial 4.0 International" to SPDXLicense.CC_BY_NC_4_0,
        "Creative Commons Attribution Non Commercial No Derivatives 1.0 Generic" to SPDXLicense.CC_BY_NC_ND_1_0,
        "Creative Commons Attribution Non Commercial No Derivatives 2.0 Generic" to SPDXLicense.CC_BY_NC_ND_2_0,
        "Creative Commons Attribution Non Commercial No Derivatives 2.5 Generic" to SPDXLicense.CC_BY_NC_ND_2_5,
        "Creative Commons Attribution Non Commercial No Derivatives 3.0 Unported" to SPDXLicense.CC_BY_NC_ND_3_0,
        "Creative Commons Attribution Non Commercial No Derivatives 4.0 International" to SPDXLicense.CC_BY_NC_ND_4_0,
        "Creative Commons Attribution Non Commercial Share Alike 1.0 Generic" to SPDXLicense.CC_BY_NC_SA_1_0,
        "Creative Commons Attribution Non Commercial Share Alike 2.0 Generic" to SPDXLicense.CC_BY_NC_SA_2_0,
        "Creative Commons Attribution Non Commercial Share Alike 2.5 Generic" to SPDXLicense.CC_BY_NC_SA_2_5,
        "Creative Commons Attribution Non Commercial Share Alike 3.0 Unported" to SPDXLicense.CC_BY_NC_SA_3_0,
        "Creative Commons Attribution Non Commercial Share Alike 4.0 International" to SPDXLicense.CC_BY_NC_SA_4_0,
        "Creative Commons Attribution No Derivatives 1.0 Generic" to SPDXLicense.CC_BY_ND_1_0,
        "Creative Commons Attribution No Derivatives 2.0 Generic" to SPDXLicense.CC_BY_ND_2_0,
        "Creative Commons Attribution No Derivatives 2.5 Generic" to SPDXLicense.CC_BY_ND_2_5,
        "Creative Commons Attribution No Derivatives 3.0 Unported" to SPDXLicense.CC_BY_ND_3_0,
        "Creative Commons Attribution No Derivatives 4.0 International" to SPDXLicense.CC_BY_ND_4_0,
        "Creative Commons Attribution Share Alike 1.0 Generic" to SPDXLicense.CC_BY_SA_1_0,
        "Creative Commons Attribution Share Alike 2.0 Generic" to SPDXLicense.CC_BY_SA_2_0,
        "Creative Commons Attribution Share Alike 2.5 Generic" to SPDXLicense.CC_BY_SA_2_5,
        "Creative Commons Attribution Share Alike 3.0 Unported" to SPDXLicense.CC_BY_SA_3_0,
        "Creative Commons Attribution Share Alike 4.0 International" to SPDXLicense.CC_BY_SA_4_0,
        "Creative Commons Public Domain Dedication and Certification" to SPDXLicense.CC_PDDC,
        "Creative Commons Zero v1.0 Universal" to SPDXLicense.CC0_1_0,
        "Common Development and Distribution License 1.0" to SPDXLicense.CDDL_1_0,
        "Common Development and Distribution License 1.1" to SPDXLicense.CDDL_1_1,
        "Community Data License Agreement Permissive 1.0" to SPDXLicense.CDLA_PERMISSIVE_1_0,
        "Community Data License Agreement Sharing 1.0" to SPDXLicense.CDLA_SHARING_1_0,
        "CeCILL Free Software License Agreement v1.0" to SPDXLicense.CECILL_1_0,
        "CeCILL Free Software License Agreement v1.1" to SPDXLicense.CECILL_1_1,
        "CeCILL Free Software License Agreement v2.0" to SPDXLicense.CECILL_2_0,
        "CeCILL Free Software License Agreement v2.1" to SPDXLicense.CECILL_2_1,
        "CeCILL-B Free Software License Agreement" to SPDXLicense.CECILL_B,
        "CeCILL-C Free Software License Agreement" to SPDXLicense.CECILL_C,
        "CERN Open Hardware Licence v1.1" to SPDXLicense.CERN_OHL_1_1,
        "CERN Open Hardware Licence v1.2" to SPDXLicense.CERN_OHL_1_2,
        "Clarified Artistic License" to SPDXLicense.CLARTISTIC,
        "CNRI Jython License" to SPDXLicense.CNRI_JYTHON,
        "CNRI Python License" to SPDXLicense.CNRI_PYTHON,
        "CNRI Python Open Source GPL Compatible License Agreement" to SPDXLicense.CNRI_PYTHON_GPL_COMPATIBLE,
        "Condor Public License v1.1" to SPDXLicense.CONDOR_1_1,
        "copyleft-next 0.3.0" to SPDXLicense.COPYLEFT_NEXT_0_3_0,
        "copyleft-next 0.3.1" to SPDXLicense.COPYLEFT_NEXT_0_3_1,
        "Common Public Attribution License 1.0" to SPDXLicense.CPAL_1_0,
        "Common Public License 1.0" to SPDXLicense.CPL_1_0,
        "Code Project Open License 1.02" to SPDXLicense.CPOL_1_02,
        "Crossword License" to SPDXLicense.CROSSWORD,
        "CrystalStacker License" to SPDXLicense.CRYSTALSTACKER,
        "CUA Office Public License v1.0" to SPDXLicense.CUA_OPL_1_0,
        "Cube License" to SPDXLicense.CUBE,
        "curl License" to SPDXLicense.CURL,
        "Deutsche Freie Software Lizenz" to SPDXLicense.D_FSL_1_0,
        "diffmark license" to SPDXLicense.DIFFMARK,
        "DOC License" to SPDXLicense.DOC,
        "Dotseqn License" to SPDXLicense.DOTSEQN,
        "DSDP License" to SPDXLicense.DSDP,
        "dvipdfm License" to SPDXLicense.DVIPDFM,
        "Educational Community License v1.0" to SPDXLicense.ECL_1_0,
        "Educational Community License v2.0" to SPDXLicense.ECL_2_0,
        "Eiffel Forum License v1.0" to SPDXLicense.EFL_1_0,
        "Eiffel Forum License v2.0" to SPDXLicense.EFL_2_0,
        "eGenix.com Public License 1.1.0" to SPDXLicense.EGENIX,
        "Entessa Public License v1.0" to SPDXLicense.ENTESSA,
        "Eclipse Public License 1.0" to SPDXLicense.EPL_1_0,
        "Eclipse Public License 2.0" to SPDXLicense.EPL_2_0,
        "Erlang Public License v1.1" to SPDXLicense.ERLPL_1_1,
        "Etalab Open License 2.0" to SPDXLicense.ETALAB_2_0,
        "EU DataGrid Software License" to SPDXLicense.EUDATAGRID,
        "European Union Public License 1.0" to SPDXLicense.EUPL_1_0,
        "European Union Public License 1.1" to SPDXLicense.EUPL_1_1,
        "European Union Public License 1.2" to SPDXLicense.EUPL_1_2,
        "Eurosym License" to SPDXLicense.EUROSYM,
        "Fair License" to SPDXLicense.FAIR,
        "Frameworx Open License 1.0" to SPDXLicense.FRAMEWORX_1_0,
        "FreeImage Public License v1.0" to SPDXLicense.FREEIMAGE,
        "FSF All Permissive License" to SPDXLicense.FSFAP,
        "FSF Unlimited License" to SPDXLicense.FSFUL,
        "FSF Unlimited License (with License Retention)" to SPDXLicense.FSFULLR,
        "Freetype Project License" to SPDXLicense.FTL,
        "GNU Free Documentation License v1.1 only" to SPDXLicense.GFDL_1_1_ONLY,
        "GNU Free Documentation License v1.1 or later" to SPDXLicense.GFDL_1_1_OR_LATER,
        "GNU Free Documentation License v1.2 only" to SPDXLicense.GFDL_1_2_ONLY,
        "GNU Free Documentation License v1.2 or later" to SPDXLicense.GFDL_1_2_OR_LATER,
        "GNU Free Documentation License v1.3 only" to SPDXLicense.GFDL_1_3_ONLY,
        "GNU Free Documentation License v1.3 or later" to SPDXLicense.GFDL_1_3_OR_LATER,
        "Giftware License" to SPDXLicense.GIFTWARE,
        "GL2PS License" to SPDXLicense.GL2PS,
        "3dfx Glide License" to SPDXLicense.GLIDE,
        "Glulxe License" to SPDXLicense.GLULXE,
        "gnuplot License" to SPDXLicense.GNUPLOT,
        "GNU General Public License v1.0 only" to SPDXLicense.GPL_1_0_ONLY,
        "GNU General Public License v1.0 or later" to SPDXLicense.GPL_1_0_OR_LATER,
        "GNU General Public License v2.0 only" to SPDXLicense.GPL_2_0_ONLY,
        "GNU General Public License v2.0 or later" to SPDXLicense.GPL_2_0_OR_LATER,
        "GNU General Public License v3.0 only" to SPDXLicense.GPL_3_0_ONLY,
        "GNU General Public License v3.0 or later" to SPDXLicense.GPL_3_0_OR_LATER,
        "gSOAP Public License v1.3b" to SPDXLicense.GSOAP_1_3B,
        "Haskell Language Report License" to SPDXLicense.HASKELLREPORT,
        "Historical Permission Notice and Disclaimer" to SPDXLicense.HPND,
        "Historical Permission Notice and Disclaimer - sell variant" to SPDXLicense.HPND_SELL_VARIANT,
        "IBM PowerPC Initialization and Boot Software" to SPDXLicense.IBM_PIBS,
        "ICU License" to SPDXLicense.ICU,
        "Independent JPEG Group License" to SPDXLicense.IJG,
        "ImageMagick License" to SPDXLicense.IMAGEMAGICK,
        "iMatix Standard Function Library Agreement" to SPDXLicense.IMATIX,
        "Imlib2 License" to SPDXLicense.IMLIB2,
        "Info-ZIP License" to SPDXLicense.INFO_ZIP,
        "Intel Open Source License" to SPDXLicense.INTEL,
        "Intel ACPI Software License Agreement" to SPDXLicense.INTEL_ACPI,
        "Interbase Public License v1.0" to SPDXLicense.INTERBASE_1_0,
        "IPA Font License" to SPDXLicense.IPA,
        "IBM Public License v1.0" to SPDXLicense.IPL_1_0,
        "ISC License" to SPDXLicense.ISC,
        "JasPer License" to SPDXLicense.JASPER_2_0,
        "Japan Network Information Center License" to SPDXLicense.JPNIC,
        "JSON License" to SPDXLicense.JSON,
        "Licence Art Libre 1.2" to SPDXLicense.LAL_1_2,
        "Licence Art Libre 1.3" to SPDXLicense.LAL_1_3,
        "Latex2e License" to SPDXLicense.LATEX2E,
        "Leptonica License" to SPDXLicense.LEPTONICA,
        "GNU Library General Public License v2 only" to SPDXLicense.LGPL_2_0_ONLY,
        "GNU Library General Public License v2 or later" to SPDXLicense.LGPL_2_0_OR_LATER,
        "GNU Lesser General Public License v2.1 only" to SPDXLicense.LGPL_2_1_ONLY,
        "GNU Lesser General Public License v2.1 or later" to SPDXLicense.LGPL_2_1_OR_LATER,
        "GNU Lesser General Public License v3.0 only" to SPDXLicense.LGPL_3_0_ONLY,
        "GNU Lesser General Public License v3.0 or later" to SPDXLicense.LGPL_3_0_OR_LATER,
        "Lesser General Public License For Linguistic Resources" to SPDXLicense.LGPLLR,
        "libpng License" to SPDXLicense.LIBPNG,
        "PNG Reference Library version 2" to SPDXLicense.LIBPNG_2_0,
        "libtiff License" to SPDXLicense.LIBTIFF,
        "Licence Libre du Québec – Permissive version 1.1" to SPDXLicense.LILIQ_P_1_1,
        "Licence Libre du Québec – Réciprocité version 1.1" to SPDXLicense.LILIQ_R_1_1,
        "Licence Libre du Québec – Réciprocité forte version 1.1" to SPDXLicense.LILIQ_RPLUS_1_1,
        "Linux Kernel Variant of OpenIB.org license" to SPDXLicense.LINUX_OPENIB,
        "Lucent Public License Version 1.0" to SPDXLicense.LPL_1_0,
        "Lucent Public License v1.02" to SPDXLicense.LPL_1_02,
        "LaTeX Project Public License v1.0" to SPDXLicense.LPPL_1_0,
        "LaTeX Project Public License v1.1" to SPDXLicense.LPPL_1_1,
        "LaTeX Project Public License v1.2" to SPDXLicense.LPPL_1_2,
        "LaTeX Project Public License v1.3a" to SPDXLicense.LPPL_1_3A,
        "LaTeX Project Public License v1.3c" to SPDXLicense.LPPL_1_3C,
        "MakeIndex License" to SPDXLicense.MAKEINDEX,
        "The MirOS Licence" to SPDXLicense.MIROS,
        "MIT" to SPDXLicense.MIT,
        "MIT License" to SPDXLicense.MIT,
        "MIT No Attribution" to SPDXLicense.MIT_0,
        "Enlightenment License (e16)" to SPDXLicense.MIT_ADVERTISING,
        "CMU License" to SPDXLicense.MIT_CMU,
        "enna License" to SPDXLicense.MIT_ENNA,
        "feh License" to SPDXLicense.MIT_FEH,
        "MIT +no-false-attribs license" to SPDXLicense.MITNFA,
        "Motosoto License" to SPDXLicense.MOTOSOTO,
        "mpich2 License" to SPDXLicense.MPICH2,
        "Mozilla Public License 1.0" to SPDXLicense.MPL_1_0,
        "Mozilla Public License 1.1" to SPDXLicense.MPL_1_1,
        "Mozilla Public License 2.0" to SPDXLicense.MPL_2_0,
        "Mozilla Public License 2.0 (no copyleft exception)" to SPDXLicense.MPL_2_0_NO_COPYLEFT_EXCEPTION,
        "Microsoft Public License" to SPDXLicense.MS_PL,
        "Microsoft Reciprocal License" to SPDXLicense.MS_RL,
        "Matrix Template Library License" to SPDXLicense.MTLL,
        "Mulan Permissive Software License, Version 1" to SPDXLicense.MULANPSL_1_0,
        "Multics License" to SPDXLicense.MULTICS,
        "Mup License" to SPDXLicense.MUP,
        "NASA Open Source Agreement 1.3" to SPDXLicense.NASA_1_3,
        "Naumen Public License" to SPDXLicense.NAUMEN,
        "Net Boolean Public License v1" to SPDXLicense.NBPL_1_0,
        "University of Illinois/NCSA Open Source License" to SPDXLicense.NCSA,
        "Net-SNMP License" to SPDXLicense.NET_SNMP,
        "NetCDF license" to SPDXLicense.NETCDF,
        "Newsletr License" to SPDXLicense.NEWSLETR,
        "Nethack General Public License" to SPDXLicense.NGPL,
        "Norwegian Licence for Open Government Data" to SPDXLicense.NLOD_1_0,
        "No Limit Public License" to SPDXLicense.NLPL,
        "Nokia Open Source License" to SPDXLicense.NOKIA,
        "Netizen Open Source License" to SPDXLicense.NOSL,
        "Noweb License" to SPDXLicense.NOWEB,
        "Netscape Public License v1.0" to SPDXLicense.NPL_1_0,
        "Netscape Public License v1.1" to SPDXLicense.NPL_1_1,
        "Non-Profit Open Software License 3.0" to SPDXLicense.NPOSL_3_0,
        "NRL License" to SPDXLicense.NRL,
        "NTP License" to SPDXLicense.NTP,
        "Open CASCADE Technology Public License" to SPDXLicense.OCCT_PL,
        "OCLC Research Public License 2.0" to SPDXLicense.OCLC_2_0,
        "ODC Open Database License v1.0" to SPDXLicense.ODBL_1_0,
        "Open Data Commons Attribution License v1.0" to SPDXLicense.ODC_BY_1_0,
        "SIL Open Font License 1.0" to SPDXLicense.OFL_1_0,
        "SIL Open Font License 1.1" to SPDXLicense.OFL_1_1,
        "Open Government Licence - Canada" to SPDXLicense.OGL_CANADA_2_0,
        "Open Government Licence v1.0" to SPDXLicense.OGL_UK_1_0,
        "Open Government Licence v2.0" to SPDXLicense.OGL_UK_2_0,
        "Open Government Licence v3.0" to SPDXLicense.OGL_UK_3_0,
        "Open Group Test Suite License" to SPDXLicense.OGTSL,
        "Open LDAP Public License v1.1" to SPDXLicense.OLDAP_1_1,
        "Open LDAP Public License v1.2" to SPDXLicense.OLDAP_1_2,
        "Open LDAP Public License v1.3" to SPDXLicense.OLDAP_1_3,
        "Open LDAP Public License v1.4" to SPDXLicense.OLDAP_1_4,
        "Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)" to SPDXLicense.OLDAP_2_0,
        "Open LDAP Public License v2.0.1" to SPDXLicense.OLDAP_2_0_1,
        "Open LDAP Public License v2.1" to SPDXLicense.OLDAP_2_1,
        "Open LDAP Public License v2.2" to SPDXLicense.OLDAP_2_2,
        "Open LDAP Public License v2.2.1" to SPDXLicense.OLDAP_2_2_1,
        "Open LDAP Public License 2.2.2" to SPDXLicense.OLDAP_2_2_2,
        "Open LDAP Public License v2.3" to SPDXLicense.OLDAP_2_3,
        "Open LDAP Public License v2.4" to SPDXLicense.OLDAP_2_4,
        "Open LDAP Public License v2.5" to SPDXLicense.OLDAP_2_5,
        "Open LDAP Public License v2.6" to SPDXLicense.OLDAP_2_6,
        "Open LDAP Public License v2.7" to SPDXLicense.OLDAP_2_7,
        "Open LDAP Public License v2.8" to SPDXLicense.OLDAP_2_8,
        "Open Market License" to SPDXLicense.OML,
        "OpenSSL License" to SPDXLicense.OPENSSL,
        "Open Public License v1.0" to SPDXLicense.OPL_1_0,
        "OSET Public License version 2.1" to SPDXLicense.OSET_PL_2_1,
        "Open Software License 1.0" to SPDXLicense.OSL_1_0,
        "Open Software License 1.1" to SPDXLicense.OSL_1_1,
        "Open Software License 2.0" to SPDXLicense.OSL_2_0,
        "Open Software License 2.1" to SPDXLicense.OSL_2_1,
        "Open Software License 3.0" to SPDXLicense.OSL_3_0,
        "The Parity Public License 6.0.0" to SPDXLicense.PARITY_6_0_0,
        "ODC Public Domain Dedication & License 1.0" to SPDXLicense.PDDL_1_0,
        "PHP License v3.0" to SPDXLicense.PHP_3_0,
        "PHP License v3.01" to SPDXLicense.PHP_3_01,
        "Plexus Classworlds License" to SPDXLicense.PLEXUS,
        "PostgreSQL License" to SPDXLicense.POSTGRESQL,
        "psfrag License" to SPDXLicense.PSFRAG,
        "psutils License" to SPDXLicense.PSUTILS,
        "Public Domain" to SPDXLicense.PUBLIC_DOMAIN,
        "Python License 2.0" to SPDXLicense.PYTHON_2_0,
        "Qhull License" to SPDXLicense.QHULL,
        "Q Public License 1.0" to SPDXLicense.QPL_1_0,
        "Rdisc License" to SPDXLicense.RDISC,
        "Red Hat eCos Public License v1.1" to SPDXLicense.RHECOS_1_1,
        "Reciprocal Public License 1.1" to SPDXLicense.RPL_1_1,
        "Reciprocal Public License 1.5" to SPDXLicense.RPL_1_5,
        "RealNetworks Public Source License v1.0" to SPDXLicense.RPSL_1_0,
        "RSA Message-Digest License" to SPDXLicense.RSA_MD,
        "Ricoh Source Code Public License" to SPDXLicense.RSCPL,
        "Ruby License" to SPDXLicense.RUBY,
        "Sax Public Domain Notice" to SPDXLicense.SAX_PD,
        "Saxpath License" to SPDXLicense.SAXPATH,
        "SCEA Shared Source License" to SPDXLicense.SCEA,
        "Sendmail License" to SPDXLicense.SENDMAIL,
        "Sendmail License 8.23" to SPDXLicense.SENDMAIL_8_23,
        "SGI Free Software License B v1.0" to SPDXLicense.SGI_B_1_0,
        "SGI Free Software License B v1.1" to SPDXLicense.SGI_B_1_1,
        "SGI Free Software License B v2.0" to SPDXLicense.SGI_B_2_0,
        "Solderpad Hardware License v0.5" to SPDXLicense.SHL_0_5,
        "Solderpad Hardware License, Version 0.51" to SPDXLicense.SHL_0_51,
        "Simple Public License 2.0" to SPDXLicense.SIMPL_2_0,
        "Sun Industry Standards Source License v1.1" to SPDXLicense.SISSL,
        "Sun Industry Standards Source License v1.2" to SPDXLicense.SISSL_1_2,
        "Sleepycat License" to SPDXLicense.SLEEPYCAT,
        "Standard ML of New Jersey License" to SPDXLicense.SMLNJ,
        "Secure Messaging Protocol Public License" to SPDXLicense.SMPPL,
        "SNIA Public License 1.1" to SPDXLicense.SNIA,
        "Spencer License 86" to SPDXLicense.SPENCER_86,
        "Spencer License 94" to SPDXLicense.SPENCER_94,
        "Spencer License 99" to SPDXLicense.SPENCER_99,
        "Sun Public License v1.0" to SPDXLicense.SPL_1_0,
        "SSH OpenSSH license" to SPDXLicense.SSH_OPENSSH,
        "SSH short notice" to SPDXLicense.SSH_SHORT,
        "Server Side Public License, v 1" to SPDXLicense.SSPL_1_0,
        "SugarCRM Public License v1.1.3" to SPDXLicense.SUGARCRM_1_1_3,
        "Scheme Widget Library (SWL) Software License Agreement" to SPDXLicense.SWL,
        "TAPR Open Hardware License v1.0" to SPDXLicense.TAPR_OHL_1_0,
        "TCL/TK License" to SPDXLicense.TCL,
        "TCP Wrappers License" to SPDXLicense.TCP_WRAPPERS,
        "TMate Open Source License" to SPDXLicense.TMATE,
        "TORQUE v2.5+ Software License v1.1" to SPDXLicense.TORQUE_1_1,
        "Trusster Open Source License" to SPDXLicense.TOSL,
        "Technische Universitaet Berlin License 1.0" to SPDXLicense.TU_BERLIN_1_0,
        "Technische Universitaet Berlin License 2.0" to SPDXLicense.TU_BERLIN_2_0,
        "Upstream Compatibility License v1.0" to SPDXLicense.UCL_1_0,
        "Unicode License Agreement - Data Files and Software (2015)" to SPDXLicense.UNICODE_DFS_2015,
        "Unicode License Agreement - Data Files and Software (2016)" to SPDXLicense.UNICODE_DFS_2016,
        "Unicode Terms of Use" to SPDXLicense.UNICODE_TOU,
        "The Unlicense" to SPDXLicense.UNLICENSE,
        "Universal Permissive License v1.0" to SPDXLicense.UPL_1_0,
        "Vim License" to SPDXLicense.VIM,
        "VOSTROM Public License for Open Source" to SPDXLicense.VOSTROM,
        "Vovida Software License v1.0" to SPDXLicense.VSL_1_0,
        "W3C Software Notice and License (2002-12-31)" to SPDXLicense.W3C,
        "W3C Software Notice and License (1998-07-20)" to SPDXLicense.W3C_19980720,
        "W3C Software Notice and Document License (2015-05-13)" to SPDXLicense.W3C_20150513,
        "Sybase Open Watcom Public License 1.0" to SPDXLicense.WATCOM_1_0,
        "Wsuipa License" to SPDXLicense.WSUIPA,
        "Do What The F*ck You Want To Public License" to SPDXLicense.WTFPL,
        "X11 License" to SPDXLicense.X11,
        "Xerox License" to SPDXLicense.XEROX,
        "XFree86 License 1.1" to SPDXLicense.XFREE86_1_1,
        "xinetd License" to SPDXLicense.XINETD,
        "X.Net License" to SPDXLicense.XNET,
        "XPP License" to SPDXLicense.XPP,
        "XSkat License" to SPDXLicense.XSKAT,
        "Yahoo! Public License v1.0" to SPDXLicense.YPL_1_0,
        "Yahoo! Public License v1.1" to SPDXLicense.YPL_1_1,
        "Zed License" to SPDXLicense.ZED,
        "Zend License v2.0" to SPDXLicense.ZEND_2_0,
        "Zimbra Public License v1.3" to SPDXLicense.ZIMBRA_1_3,
        "Zimbra Public License v1.4" to SPDXLicense.ZIMBRA_1_4,
        "zlib License" to SPDXLicense.ZLIB,
        "zlib/libpng License with Acknowledgement" to SPDXLicense.ZLIB_ACKNOWLEDGEMENT,
        "Zope Public License 1.1" to SPDXLicense.ZPL_1_1,
        "Zope Public License 2.0" to SPDXLicense.ZPL_2_0,
        "Zope Public License 2.1" to SPDXLicense.ZPL_2_1
    )

    private val nameList = nameMap.keys
    private val identifierList = nameMap.values.map { it.csvName }
}
