logs:
  - id: rum_view_ended
    message: "[Mobile Metric] RUM View Ended"
    type: metric
    sampleRate: 0.75
    properties:
      metric_type:
        type: string
        const: "rum view ended"
      rve:
        type: object
        properties:
          duration:
            type: long
            nullable: true
          loading_time:
            type: object
            nullable: true
            properties:
              value:
                type: long
                nullable: true
          view_type:
            type: enum
            values:
              - custom
              - background
              - application_launch
          tns:
            type: object
            properties:
              value:
                type: long
                nullable: true
              config:
                type: enum
                values:
                  - disabled
                  - time_based_default
                  - time_based_custom
                  - custom
              no_value_reason:
                type: enum
                nullable: true
                values:
                  - unknown
                  - no_resources
                  - no_initial_resources
                  - not_settled_yet
          inv:
            type: object
            properties:
              value:
                type: long
                nullable: true
              config:
                type: enum
                values:
                  - disabled
                  - time_based_default
                  - time_based_custom
                  - custom
              no_value_reason:
                type: enum
                nullable: true
                values:
                  - unknown
                  - no_action
                  - no_eligible_action
                  - no_previous_view
                  - disabled
          instrumentation_type:
            type: string

  - id: app_launch_ttid
    message: "[Mobile Metric] App Launch TTID"
    type: metric
    sampleRate: 15.0
    properties:
      metric_type:
        type: string
        const: "app launch ttid"
      app_launch_ttid:
        type: object
        properties:
          scenario:
            type: string
          duration_ns:
            type: long
          index_in_session:
            type: int
          cp_process_start_diff_ns:
            type: long
          process_start_importance:
            type: int
          has_saved_instance_state:
            type: boolean
          app_start_activity_on_create_gap_ns:
            type: long
            nullable: true

  - id: ui_slowness
    message: "[Mobile Metric] RUM UI Slowness"
    type: metric
    sampleRate: 0.75
    properties:
      metric_type:
        type: string
        const: "rum ui slowness"
      rum_ui_slowness:
        type: object
        properties:
          view_duration:
            type: long
          slow_frames:
            type: object
            properties:
              count:
                type: int
              ignored_count:
                type: int
              missed_count:
                type: int
              config:
                type: object
                properties:
                  max_count:
                    type: int
                  slow_frame_threshold:
                    type: float
                    const: 2.0
                  max_duration:
                    type: long
                  view_min_duration:
                    type: long

  - id: report_app_fully_displayed_called_too_early
    message: "RumMonitor.reportAppFullyDisplayed was called before the application launch was detected, ignoring it."
    type: log
    level: error
    targets:
      - user

  - id: report_app_fully_displayed_called_before_ttid
    message: "RumMonitor.reportAppFullyDisplayed was called before TTID was computed, will report TTID as TTFD."
    type: log
    level: warn
    targets:
      - user

  - id: ttfd_too_large
    message: "TTFD value is too large, skipping it"
    type: log
    level: warn
    targets:
      - user
      - telemetry

  - id: ttid_too_large
    message: "TTID value is too large, skipping it"
    type: log
    level: warn
    targets:
      - user
      - telemetry
