logs:
  - id: rum_view_ended
    message: "[Mobile Metric] RUM View Ended"
    type: metric
    sampleRate: 0.75
    creationSampleRate: 100
    properties:
      metric_type:
        type: string
        const: "rum view ended"
      rve:
        type: object
        properties:
          duration:
            type: long
            nullable: true
          loading_time:
            type: object
            nullable: true
            properties:
              value:
                type: long
                nullable: true
          view_type:
            type: enum
            values:
              - custom
              - background
              - application_launch
          tns:
            type: object
            properties:
              value:
                type: long
                nullable: true
              config:
                type: enum
                values:
                  - disabled
                  - time_based_default
                  - time_based_custom
                  - custom
              no_value_reason:
                type: enum
                nullable: true
                values:
                  - unknown
                  - no_resources
                  - no_initial_resources
                  - not_settled_yet
          inv:
            type: object
            properties:
              value:
                type: long
                nullable: true
              config:
                type: enum
                values:
                  - disabled
                  - time_based_default
                  - time_based_custom
                  - custom
              no_value_reason:
                type: enum
                nullable: true
                values:
                  - unknown
                  - no_action
                  - no_eligible_action
                  - no_previous_view
                  - disabled
          instrumentation_type:
            type: string

  - id: app_launch_ttid
    message: "[Mobile Metric] App Launch TTID"
    type: metric
    sampleRate: 15.0
    creationSampleRate: 100
    properties:
      metric_type:
        type: string
        const: "app launch ttid"
      app_launch_ttid:
        type: object
        properties:
          scenario:
            type: string
          duration_ns:
            type: long
          index_in_session:
            type: int
          cp_process_start_diff_ns:
            type: long
          process_start_importance:
            type: int
          has_saved_instance_state:
            type: boolean
          app_start_activity_on_create_gap_ns:
            type: long
            nullable: true

  - id: ui_slowness
    message: "[Mobile Metric] RUM UI Slowness"
    type: metric
    sampleRate: 0.75
    creationSampleRate: 100
    properties:
      metric_type:
        type: string
        const: "rum ui slowness"
      rum_ui_slowness:
        type: object
        properties:
          view_duration:
            type: long
          slow_frames:
            type: object
            properties:
              count:
                type: int
              ignored_count:
                type: int
              missed_count:
                type: int
              config:
                type: object
                properties:
                  max_count:
                    type: int
                  slow_frame_threshold:
                    type: float
                    const: 2.0
                  max_duration:
                    type: long
                  view_min_duration:
                    type: long

  - id: gap_between_views
    message: "[Mobile Metric] Gap between views"
    type: metric
    sampleRate: 1.0
    creationSampleRate: 100
    properties:
      view_gap:
        type: long

  - id: negative_gap_between_views
    message: "[Mobile Metric] Negative gap between views"
    type: metric
    sampleRate: 1.0
    creationSampleRate: 100
    properties:
      view_gap:
        type: long

  - id: rum_session_ended
    message: "[Mobile Metric] RUM Session Ended"
    type: metric
    sampleRate: 15.0
    properties:
      metric_type:
        type: string
        const: "rum session ended"
      rse:
        type: object
        properties:
          process_type:
            type: string
            const: "app"
          precondition:
            type: string
          duration:
            type: long
          was_stopped:
            type: boolean
          views_count:
            type: object
            properties:
              total:
                type: int
              background:
                type: int
              app_launch:
                type: int
              with_has_replay:
                type: int
          sdk_errors_count:
            type: object
            properties:
              total:
                type: int
              by_kind:
                type: map
                value_type: int
          no_view_events_count:
            type: object
            properties:
              actions:
                type: int
              resources:
                type: int
              errors:
                type: int
              long_tasks:
                type: int
          has_background_events_tracking_enabled:
            type: boolean
          ntp_offset:
            type: object
            properties:
              at_start:
                type: long
              at_end:
                type: long
          sr_skipped_frames_count:
            type: int

  - id: report_app_fully_displayed_called_too_early
    message: "RumMonitor.reportAppFullyDisplayed was called before the application launch was detected, ignoring it."
    type: log
    level: error
    targets:
      - user

  - id: report_app_fully_displayed_called_before_ttid
    message: "RumMonitor.reportAppFullyDisplayed was called before TTID was computed, will report TTID as TTFD."
    type: log
    level: warn
    targets:
      - user

  - id: ttfd_too_large
    message: "TTFD value is too large, skipping it"
    type: log
    level: warn
    targets:
      - user
      - telemetry

  - id: ttid_too_large
    message: "TTID value is too large, skipping it"
    type: log
    level: warn
    targets:
      - user
      - telemetry
