/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2016-Present Datadog, Inc.
 */

package com.datadog.tools.diff

import com.google.devtools.ksp.getDeclaredProperties
import com.google.devtools.ksp.getVisibility
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.Visibility
import com.google.devtools.ksp.validate
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeName
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo

private enum class DiffStrategy { REPLACE, MERGE, IGNORE, APPEND }

private data class PropertyInfo(
    val name: String,
    val typeName: TypeName,
    val strategy: DiffStrategy,
    val mergeClassDecl: KSClassDeclaration?,
)

class DiffProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    companion object {
        private val DIFF_OPTIONAL = ClassName("com.datadog.tools.diff", "DiffOptional")
        private val MAKE_DIFF = MemberName("com.datadog.tools.diff", "makeDiff")
        private val WRAP_OPTIONAL = MemberName("com.datadog.tools.diff", "wrapOptional")
    }

    override fun process(resolver: Resolver): List<KSAnnotated> {
        val symbols = resolver.getSymbolsWithAnnotation(Diff::class.qualifiedName!!)
        val (valid, deferred) = symbols.partition { it.validate() }

        valid.filterIsInstance<KSClassDeclaration>().forEach { classDecl ->
            logger.info("DiffPlugin: processing @Diff class ${classDecl.qualifiedName?.asString()}")
            generateDiffFor(classDecl)
        }

        return deferred
    }

    private fun generateDiffFor(classDecl: KSClassDeclaration) {
        val packageName = classDecl.packageName.asString()
        val className = classDecl.simpleName.asString()
        val sourceType = classDecl.toClassName()
        val diffType = ClassName(packageName, "${className}Diff")
        val visibility = classDecl.getVisibility().toKModifier()

        val propInfos = classDecl.getDeclaredProperties().map { prop ->
            val typeName = prop.type.toTypeName()
            val annotations = prop.annotations.map { it.shortName.asString() }.toSet()
            val strategy = when {
                annotations.contains("DiffIgnore") -> DiffStrategy.IGNORE
                annotations.contains("DiffAppend") -> DiffStrategy.APPEND
                annotations.contains("DiffMerge") -> DiffStrategy.MERGE
                else -> DiffStrategy.REPLACE
            }
            val resolvedType = prop.type.resolve()
            PropertyInfo(
                name = prop.simpleName.asString(),
                typeName = typeName,
                strategy = strategy,
                mergeClassDecl = if (strategy == DiffStrategy.MERGE) resolvedType.declaration as? KSClassDeclaration else null,
            )
        }.toList()

        val fileBuilder = FileSpec.builder(packageName, "${className}Diff")
            .addFileComment("Auto-generated by DiffPlugin — do not edit")

        // Main diff extension function
        fileBuilder.addFunction(buildMainDiffFun(sourceType, diffType, propInfos, visibility))

        // Nested diff types and extension functions for @DiffMerge properties
        val nestedTypeSpecs = mutableListOf<TypeSpec>()
        for (info in propInfos.filter { it.strategy == DiffStrategy.MERGE }) {
            val mergeDecl = info.mergeClassDecl ?: continue
            val nestedDiffSimpleName = "${mergeDecl.simpleName.asString()}Diff"
            val nestedDiffType = diffType.nestedClass(nestedDiffSimpleName)
            val mergeSourceType = mergeDecl.toClassName()
            val nestedFields = mergeDecl.getDeclaredProperties().map {
                it.simpleName.asString() to it.type.toTypeName()
            }.toList()

            fileBuilder.addFunction(
                buildNestedDiffFun(mergeSourceType, nestedDiffType, nestedFields, visibility)
            )

            nestedTypeSpecs += buildDataClass(
                name = nestedDiffSimpleName,
                fields = nestedFields.map { (n, t) -> n to DIFF_OPTIONAL.parameterizedBy(t) },
                visibility = null,
                nestedTypes = emptyList(),
            )
        }

        // Main diff data class
        val mainDiffFields = propInfos.map { info ->
            val fieldType = when (info.strategy) {
                DiffStrategy.IGNORE -> info.typeName
                DiffStrategy.REPLACE, DiffStrategy.APPEND -> DIFF_OPTIONAL.parameterizedBy(info.typeName)
                DiffStrategy.MERGE -> {
                    val nestedName = "${info.mergeClassDecl!!.simpleName.asString()}Diff"
                    DIFF_OPTIONAL.parameterizedBy(diffType.nestedClass(nestedName))
                }
            }
            info.name to fieldType
        }
        fileBuilder.addType(
            buildDataClass(
                name = "${className}Diff",
                fields = mainDiffFields,
                visibility = visibility,
                nestedTypes = nestedTypeSpecs,
            )
        )

        fileBuilder.build()
            .writeTo(codeGenerator, aggregating = false, listOf(classDecl.containingFile!!))
    }

    // --- Code generation helpers ---

    private fun buildDataClass(
        name: String,
        fields: List<Pair<String, TypeName>>,
        visibility: KModifier?,
        nestedTypes: List<TypeSpec>,
    ): TypeSpec {
        val ctor = FunSpec.constructorBuilder().apply {
            fields.forEach { (n, t) -> addParameter(n, t) }
        }.build()

        return TypeSpec.classBuilder(name)
            .addModifiers(KModifier.DATA)
            .apply { if (visibility != null) addModifiers(visibility) }
            .primaryConstructor(ctor)
            .apply {
                fields.forEach { (n, t) ->
                    addProperty(PropertySpec.builder(n, t).initializer(n).build())
                }
                nestedTypes.forEach { addType(it) }
            }
            .build()
    }

    private fun buildMainDiffFun(
        sourceType: ClassName,
        diffType: ClassName,
        propInfos: List<PropertyInfo>,
        visibility: KModifier?,
    ): FunSpec {
        val code = CodeBlock.builder()

        // Generate diff variables for REPLACE properties
        for (info in propInfos.filter { it.strategy == DiffStrategy.REPLACE }) {
            code.addStatement("val %N = %M(%N, other.%N)", "${info.name}Diff", MAKE_DIFF, info.name, info.name)
        }

        // Generate diff variables for APPEND properties
        for (info in propInfos.filter { it.strategy == DiffStrategy.APPEND }) {
            val dropped = "${info.name}Dropped"
            code.addStatement("val %N = other.%N.drop(%N.size)", dropped, info.name, info.name)
            code.beginControlFlow("val %N = if (%N.isNotEmpty())", "${info.name}Diff", dropped)
            code.addStatement("%N.%M()", dropped, WRAP_OPTIONAL)
            code.nextControlFlow("else")
            code.addStatement("%T.empty()", DIFF_OPTIONAL)
            code.endControlFlow()
        }

        // Return statement
        code.add("return %T(\n", diffType)
        code.indent()
        for ((i, info) in propInfos.withIndex()) {
            val comma = if (i < propInfos.lastIndex) "," else ""
            when (info.strategy) {
                DiffStrategy.IGNORE -> code.add("%N = other.%N$comma\n", info.name, info.name)
                DiffStrategy.REPLACE, DiffStrategy.APPEND -> code.add("%N = %N$comma\n", info.name, "${info.name}Diff")
                DiffStrategy.MERGE -> code.add("%N = %N.diff(other.%N)$comma\n", info.name, info.name, info.name)
            }
        }
        code.unindent()
        code.add(")\n")

        return FunSpec.builder("diff")
            .receiver(sourceType)
            .addParameter("other", sourceType)
            .returns(diffType)
            .apply { if (visibility != null) addModifiers(visibility) }
            .addCode(code.build())
            .build()
    }

    private fun buildNestedDiffFun(
        mergeSourceType: ClassName,
        nestedDiffType: ClassName,
        fields: List<Pair<String, TypeName>>,
        visibility: KModifier?,
    ): FunSpec {
        val returnType = DIFF_OPTIONAL.parameterizedBy(nestedDiffType)
        val code = CodeBlock.builder()

        // Generate diff variables for each property
        for ((name, _) in fields) {
            code.addStatement("val %N = %M(%N, other.%N)", "${name}Diff", MAKE_DIFF, name, name)
        }
        code.add("\n")

        // Early return if nothing changed
        val noneChanged = fields.joinToString(" && ") { (name, _) -> "!${name}Diff.exists" }
        code.beginControlFlow("if (%L)", noneChanged)
        code.addStatement("return %T.empty()", DIFF_OPTIONAL)
        code.endControlFlow()
        code.add("\n")

        // Return with all diffs
        code.add("return %T(\n", nestedDiffType)
        code.indent()
        for ((i, field) in fields.withIndex()) {
            val (name, _) = field
            val comma = if (i < fields.lastIndex) "," else ""
            code.add("%N = %N$comma\n", name, "${name}Diff")
        }
        code.unindent()
        code.add(").%M()\n", WRAP_OPTIONAL)

        return FunSpec.builder("diff")
            .receiver(mergeSourceType)
            .addParameter("other", mergeSourceType)
            .returns(returnType)
            .apply { if (visibility != null) addModifiers(visibility) }
            .addCode(code.build())
            .build()
    }

    private fun Visibility.toKModifier(): KModifier? = when (this) {
        Visibility.PUBLIC -> KModifier.PUBLIC
        Visibility.INTERNAL -> KModifier.INTERNAL
        Visibility.PRIVATE -> KModifier.PRIVATE
        Visibility.PROTECTED -> KModifier.PROTECTED
        else -> null
    }
}
