/*
 * Unless explicitly stated otherwise all files in this repository are licensed under the Apache License Version 2.0.
 * This product includes software developed at Datadog (https://www.datadoghq.com/).
 * Copyright 2016-Present Datadog, Inc.
 */

package com.datadog.android.flags.internal.model

import com.google.gson.JsonElement
import com.google.gson.JsonObject

@Suppress("TodoWithoutTask")
// TODO: Replace this class with an autogenerated class based on a json schema
internal data class ExposureEvent(
    val timeStamp: Long, // now
    val allocation: Identifier, // allocationKey from precompute
    val flag: Identifier, // flag name
    val variant: Identifier, // variationKey from precompute
    val subject: Subject
) {
    fun toJson(): String {
        val json = JsonObject()
        json.addProperty("timestamp", timeStamp)
        json.add("allocation", allocation.toJson())
        json.add("flag", flag.toJson())
        json.add("variant", variant.toJson())
        json.add("subject", subject.toJson())
        return json.toString()
    }
}

internal data class Identifier(
    val key: String
) {
    internal fun toJson(): JsonElement {
        val json = JsonObject()
        json.addProperty("key", key)
        return json
    }
}

internal data class Subject(
    val id: String, // this is the targeting_key
    val attributes: Map<String, String>
) {
    internal fun toJson(): JsonElement {
        val json = JsonObject()
        json.addProperty("id", id)

        val attributeObj = JsonObject()
        attributes.forEach { (key, value) ->
            attributeObj.addProperty(key, value)
        }
        json.add("attributes", attributeObj)
        return json
    }
}
