name: "Android Instrumented tests"

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master", "develop", "release/**", "feature/**" ]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [21, 23, 29, 34]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '17.0'
          distribution: 'adopt'
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          java-version: '17'
          api-level: ${{ matrix.api-level }}
          arch: arm64-v8a
          disable-animations: true
          script: ./gradlew :instrumented:integration:connectedCheck
