# This file creates a workflow using GitHub Actions
# CF GitHub documentation : https://help.github.com/en/actions/automating-your-workflow-with-github-actions

name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"